apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-deployment
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
       maxSurge: 1
       maxUnavailable: 25%
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      serviceAccountName: jenkins
      securityContext:
        fsGroup: 1000
        runAsUser: 0
      containers:
          - name: "jenkins-master"
            image: "keaz/jenkins-master:alpine"
            imagePullPolicy: "IfNotPresent"
            env:
              - name: JAVA_OPTS
                value: -Djenkins.install.runSetupWizard=false
            ports:
              - name: http-port
                containerPort: 8080
              - name: jnlp-port
                containerPort: 50000
            volumeMounts:
              - name: jenkins-home
                mountPath: "/var/jenkins_home"
              #- name: jenkins
        #image: jenkins/jenkins:lts
        #image: opencloudnet/jenkins-master
        #ports:
        #- containerPort: 8080
        #volumeMounts:
        # - name: jenkins-home
        #   mountPath: /var/jenkins_home
      volumes:
        - name: jenkins-home
          persistentVolumeClaim:
            claimName: "pvc-2"
           #readOnly: "false"
