apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: csi-rbd
provisioner: rbd.csi.ceph.com
parameters:
  monitors: 192.168.1.212:6789, 192.168.1.198:6789, 192.168.1.52:6789
  adminId: admin
  adminSecretName: ceph-secret
  adminSecretNamespace: kube-system
  pool: kubernetes
  clusterID: aca3a34f-f790-4d21-b3f1-e270ef83612f
  userId: kubernetes
  userSecretName: csi-rbd-secret
  userSecretNamespace: kube-system
  imageFormat: "2"
  imageFeatures: layering
