---
- name: Intilizing Kubernetes Cluster
  command: sudo kubeadm init --pod-network-cidr "{{ pod_network_cidr }}"  --apiserver-advertise-address "{{ ansible_default_ipv4.address }}" --skip-phases addon/coredns,addon/kube-proxy
  run_once: true
- pause: seconds=30
- name: Create directory for kube config.
  file: 
    path: /home/{{ ansible_user }}/.kube
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755
- name: Adding kube-proxy 
  command: sudo kubeadm init phase addon kube-proxy
  run_once: true

- name: Adding coredns 
  command: sudo kubeadm init  phase addon coredns
  run_once: true

- name: Copy /etc/kubernetes/admin.conf to ansible_user's home directory /home/{{ ansible_user }}/.kube/config.
  become_user: root
  become_method: sudo
  become: yes
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/{{ ansible_user }}/.kube/config
    remote_src: yes
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'

- pause: seconds=10

- name: Remove the cache directory.
  file: 
     path: /home/{{ ansible_user }}/.kube/cache
     state: absent

#- name: Get the token for joining the nodes with Kuberentes master.
#  shell: kubeadm token create  --print-join-command
#  register: kubernetes_join_command
#
#- debug:
#    msg: "{{ kubernetes_join_command.stdout }}"
#
#- name: Copy join command to local file.
#  local_action: copy content="{{ kubernetes_join_command.stdout_lines[0] }}" dest="/tmp/kubernetes_join_command" mode=0777
